# Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
#
# Hyprland configuration : Theme Elements & Colors ---------

# Decoration
$hypr_border_size        = 2
$hypr_gaps_in            = 5
$hypr_gaps_out           = 10
$hypr_gaps_ws            = -10
$hypr_rounding           = 0
$hypr_active_opacity     = 1.0
$hypr_inactive_opacity   = 1.0
$hypr_fullscreen_opacity = 1.0
$hypr_blur_enabled       = false
$hypr_blur_size          = 8
$hypr_blur_pass          = 3

# Windows
$gradient_angle                   = 45deg
$active_border_col_1              = 0xFFb4a1db
$active_border_col_2              = 0xFFdb86ba
$inactive_border_col_1            = 0xFF2a323b
$inactive_border_col_2            = 0xFF353f4a
$active_shadow_col                = 0x66000000
$inactive_shadow_col              = 0x66000000

# Groups 
$groupbar_font_family             = RobotoMono Nerd Font 
$groupbar_font_size               = 12
$group_border_active_col          = 0xFFb4a1db
$group_border_inactive_col        = 0xFF2a323b
$group_border_locked_active_col   = 0xFFdb86ba
$group_border_locked_inactive_col = 0xFF2a323b
$groupbar_text_color_active       = 0xFF20262C
$groupbar_text_color_inactive     = 0xFFf1fcf9

# Misc
$notifycmd = notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low
