# Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
#
# Hyprland configuration file for Archcraft
# Hyprland Version: 0.51.0
#
# For Documentation, Visit : https://wiki.hypr.land/

# Source config files
source = ~/.config/hypr/config.d/*

# Startup
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = hypridle
exec-once = ~/.config/hypr/scripts/startup
