# Shell variables
# Generated by 'wal'
wallpaper='/home/harvey/Pictures/wallpapers/porsche-car.jpg'

# Special
background='#080A28'
foreground='#b4e7f5'
cursor='#b4e7f5'

# Colors
color0='#080A28'
color1='#4632D5'
color2='#6052EA'
color3='#618DB8'
color4='#679AD3'
color5='#6EB5FC'
color6='#73CAFC'
color7='#b4e7f5'
color8='#7da1ab'
color9='#4632D5'
color10='#6052EA'
color11='#618DB8'
color12='#679AD3'
color13='#6EB5FC'
color14='#73CAFC'
color15='#b4e7f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
