#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Mako -----------------------------------------------------

CONFIG="$HOME/.config/hyprcat/mako/config"

if [[ ! `pidof mako` ]]; then
	mako --config ${CONFIG}
fi
