#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/hyprcat"
RASI="$DIR/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-theme ${RASI}
