#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Wlogout --------------------------------------------------

LAYOUT="$HOME/.config/hyprcat/wlogout/layout"
STYLE="$HOME/.config/hyprcat/wlogout/style.css"

if [[ ! `pidof wlogout` ]]; then
	wlogout --layout ${LAYOUT} --css ${STYLE} \
		--buttons-per-row 5 \
		--column-spacing 50 \
		--row-spacing 50 \
		--margin-top 390 \
		--margin-bottom 390 \
		--margin-left 150 \
		--margin-right 150
else
	pkill wlogout
fi
