#!/usr/bin/env bash

## Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
##
## Wofi Menu ------------------------------------------------

CONFIG="$HOME/.config/hyprcat/wofi/config"
STYLE="$HOME/.config/hyprcat/wofi/style.css"

if [[ ! `pidof wofi` ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE}
else
	pkill wofi
fi
