# Copyright (C) 2020-2025 Aditya Shakya <adi1090x@gmail.com>
#
# Hyprland configuration : Window Rules --------------------

# You can set window rules to achieve different window behaviors based on their properties.
#
# Syntax: windowrule=RULE,PARAMETERS
#
# RULE is a rule (and a param if applicable)
# PARAMETERS is a comma-separated list of various window attributes you can match by.

# Floating apps
windowrule = float, class: foot-float|alacritty-float|kitty-float
windowrule = float, class: yad|nm-connection-editor|org.pulseaudio.pavucontrol
windowrule = float, class: xfce-polkit|kvantummanager|qt5ct|qt6ct
windowrule = float, class: feh|viewnior|gimp|MPlayer
windowrule = float, class: VirtualBox Manager|qemu|Qemu-system-x86_64
windowrule = float, title: File Operation Progress
windowrule = float, title: Confirm to replace files

# Thunar's rename window
windowrule = float, class: thunar, title: (Rename .*)

# Yad window
windowrule = float,        class: Yad|yad
windowrule = size 60% 64%, class: Yad|yad

# Installer windows
windowrule = float,        class: io.calamares.calamares
windowrule = center,       class: io.calamares.calamares
windowrule = float,        title:^(Archcraft Installer)(.*)$

# Viewnior window
windowrule = size 60% 64%, class: viewnior
windowrule = center,       class: viewnior

# Alacritty floating geometry
windowrule = size 785 450, class: Alacritty|alacritty|alacritty-float

# Fullscreen animations
windowrule = animation slide down, class: foot-full|alacritty-full|kitty-full
windowrule = animation slide up,   class: wlogout

# ---

# Firefox
windowrule = workspace 2, class: firefox
windowrule = float, class: firefox, title: (Picture-in-Picture)
windowrule = size 50%, class: firefox, title: (Picture-in-Picture)
windowrule = move 100%-w-40 100%-w-40, class: firefox, title: (Picture-in-Picture)

# ---

# Layer Rules
#
# Syntax: layerrule = rule, namespace or layerrule = rule, address
layerrule = animation slide, rofi
layerrule = animation slide, notifications
