## Colors configuration
[colors]
alpha=1.0
foreground=b4e7f5
background=080A28

## Normal/regular colors (color palette 0-7)
regular0=080A28  # black
regular1=4632D5  # red
regular2=6052EA  # green
regular3=618DB8  # yellow
regular4=679AD3  # blue
regular5=6EB5FC  # magenta
regular6=73CAFC  # cyan
regular7=b4e7f5  # white

## Bright colors (color palette 8-15)
bright0=7da1ab   # bright black
bright1=4632D5   # bright red
bright2=6052EA   # bright green
bright3=618DB8   # bright yellow
bright4=679AD3   # bright blue
bright5=6EB5FC   # bright magenta
bright6=73CAFC   # bright cyan
bright7=b4e7f5   # bright white
